### ISSUE TITLE
RestClientBase not generating right url if one of the query param is 0

### ISSUE THREAD

**Issue by mohitbagra** [Microsoft/azure-devops-extension-api#1]
I am calling - 
```typescript
getClient(WorkItemTrackingRestClient).getClassificationNode(project.id, TreeStructureGroup.Areas, undefined, 5);
```
to load area paths. This api needs an enum parameter (TreeStructureGroup.Areas), whose value is 0.

This is not working because the url generation logic is stripping out 0 from query param string.

https://github.com/Microsoft/azure-devops-extension-api/blob/22937f8332d27f69c2e90a44a1f2eac7cea9b218/src/Common/Util/Url.ts#L714

This line here checks for !value which would return true if value is 0, which seems wrong.

**Comment by nkirchem** [comment]
Fixed in 1.144.2
