### ISSUE TITLE
Question - Work Item Tracking Process Template - Processes

### ISSUE THREAD

**Issue by dNsl9r** [Microsoft/azure-devops-extension-api#11]
Hi, I'm trying to download a Process Template as described here: https://docs.microsoft.com/en-us/rest/api/azure/devops/processadmin/processes/export%20process%20template?view=azure-devops-rest-5.1

No matter which process I try to download (System or Inherited Custom) I get the error:
> Invalid operation for an inherited process.

Which rules apply for using this API call and where can I read about this?
Thanks :-)

**Comment by bcarthic** [comment]
You cannot get inherited or system process. You can get only fully customized process if you have it enabled.

**Comment by dNsl9r** [comment]
Thank you for clarification @bcarthic ! Did not know that.
I suggest that this should be added as a hint in the documentation.
