### ISSUE TITLE
Host panel's iframe not taking full width

### ISSUE THREAD

**Issue by mohitbagra** [Microsoft/azure-devops-extension-api#4]
The iframe loaded in the host panel is not taking full width of the panel

![image](https://user-images.githubusercontent.com/3766956/49045238-5c45b880-f19e-11e8-9930-7e19791ad629.png)

**Comment by mohitbagra** [comment]
It can be fixed by adding flex-grow: 1 to the iframe's parent - 
![image](https://user-images.githubusercontent.com/3766956/49045279-81d2c200-f19e-11e8-953b-943ea4e3959c.png)

**Comment by nkirchem** [comment]
Fixed in Azure DevOps M144. Deployment should reach all rings in about 2 weeks.
