### ISSUE TITLE
Continuously get 404 (Not Found) errors when using any Rest Client.

### ISSUE THREAD

**Issue by myermian** [Microsoft/azure-devops-extension-api#5]
I downloaded the sample project (https://github.com/Microsoft/azure-devops-extension-sample) and the only modifications I had to make were:

1. Publisher Id
2. Manifest categories (It is now 'Azure Pipelines' instead of 'Pipelines').

I continuously get a 404 error no matter which client I attempt to use. The sample uses a `WorkItemTrackingRestClient`, but when I was working on my own project I tried to use the `GitRestClient` to get a list of repositories, same failure (404).

Here is a chrome dev tools log of the error from the sample:

> GET https://dev.azure.com/{organization-removed}/Samples/_apis/wit/workItemTypes 404 (Not Found)
> Failed to get items for PickList: 404: Not Found
> 

And here is the source code file from the git repo: https://github.com/Microsoft/azure-devops-extension-sample/blob/master/src/Samples/WorkItemOpen/WorkItemOpen.tsx

Oh, and at first I thought maybe I had to wait until the `SDK.ready()` fired off, so I tried using `SDK.ready().then(...)` and placed my work inside the then, but I still cannot use any rest client. The sample project doesn't even do that though, so I'm not sure if that was a dead end or not.

**Comment by SeriousM** [comment]
The problem resides in this line: https://github.com/Microsoft/azure-devops-extension-api/blob/master/src/Common/RestClientBase.ts#L155
```js
let acceptHeaderValue = `${acceptType};api-version=${apiVersion};excludeUrls=true;enumsAsNumbers=true;msDateFormat=true;noArrayWrap=true`;
```

When I remove everything except the `acceptType` the server responds as expected.
@nkirchem why is this value added? It doesn't make any sense and breaks the communication with the server.

My guess is that the server tries to negotiate the content type and can't handle the additional parameters.

**Comment by nkirchem** [comment]
@SeriousM The 5.1 REST apis were introduced in the M144 milestone which has not yet rolled through all rings (it should finish within the next week). Until that time, if you want to test on an account that has not been upgraded yet, you can consume the 1.143.0 version of the azure-devops-api package.

In the future we won't update the version of the API package that the sample uses until after our deployment has finished. Apologies for the inconvenience here.

**Comment by SeriousM** [comment]
> In the future we won't update the version of the API package that the sample uses until after our deployment has finished.

Thank you very much for clarifying this situation. It's the second time I waste many hours because of "has not yet rolled through all rings". This is really a bummer and reduces the trust in microsoft products.
Is ther *any* way to tell if my vsts/devops instance has a certain update?

**Comment by SeriousM** [comment]
> The second version segment (143) shows which milestone the account is on.

thank you so much! 🎉
