### ISSUE TITLE
CORS error when calling BuildRestClient.getBuildTags()

### ISSUE THREAD

**Issue by patriziobrunoms** [microsoft/azure-devops-extension-api#68]
I have an extension that targets ms.vss-build-web.build-results-tab. It worked until a few days ago, now it stopped and I see the following error in the console:

> Access to fetch at 'https://dev.azure.com/MyOrg/MyProject/_apis/build/builds/1980/tags' from origin 'https://my-publisher.gallerycdn.vsassets.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by patriziobrunoms** [comment]
I updated many of my dependencies and apparently now I need to provide a token provider even if the extension is querying the same org where it is installed.

**Comment by kannan-cidc** [comment]
@patriziobrunoms - can you please let me know how token provider has to be given ?
